language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y zlib1g-dev
script:
 - make clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" make V=1
